services:
  - type: web
    name: fastapi-reddit
    env: python
    buildCommand: "./venv/bin/pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DATABASE_URL
        value: <your_database_url>
      - key: SECRET_KEY
        value: your_secret_key
    build:
      pythonVersion: 3.10.12

